use std::collections::HashMap;
use std::path::Path;

use super::{GeneResult, MaskType};

/// Chromosome sizes (hg38, bp) for Manhattan plot layout.
const CHROMS: &[(&str, u64)] = &[
    ("1", 249_000_000), ("2", 243_000_000), ("3", 198_000_000),
    ("4", 190_000_000), ("5", 182_000_000), ("6", 171_000_000),
    ("7", 159_000_000), ("8", 145_000_000), ("9", 138_000_000),
    ("10", 134_000_000), ("11", 135_000_000), ("12", 133_000_000),
    ("13", 114_000_000), ("14", 107_000_000), ("15", 102_000_000),
    ("16", 90_000_000), ("17", 84_000_000), ("18", 80_000_000),
    ("19", 59_000_000), ("20", 65_000_000), ("21", 47_000_000),
    ("22", 51_000_000), ("X", 156_000_000), ("Y", 57_000_000),
];

/// Genome-wide significance: Bonferroni correction for ~20K protein-coding genes.
const SIGNIFICANCE: f64 = 2.5e-6;
/// Conventional suggestive threshold for GWAS follow-up.
const SUGGESTIVE: f64 = 5e-4;

struct PlotPoint {
    x: f64,
    y: f64,
    chrom_idx: usize,
    label: String,
}

/// Generate self-contained HTML summary report from STAAR results.
pub fn generate_report(
    results: &[(MaskType, Vec<GeneResult>)],
    traits: &[String],
    n_samples: usize,
    n_rare: i64,
    output_dir: &Path,
    title: &str,
) -> std::io::Result<()> {
    let points = layout_points(results);
    let all_pvals = collect_pvalues(results);
    let top_hits = top_genes(results, SIGNIFICANCE);

    let n_genes: usize = results.iter().map(|(_, r)| r.len()).sum();
    let n_sig = top_hits.len();
    let masks: Vec<String> = results.iter()
        .filter(|(_, r)| !r.is_empty())
        .map(|(m, _)| m.file_stem())
        .collect();

    let manhattan = manhattan_svg(&points);
    let qq = qq_svg(&all_pvals);
    let table = hits_table(&top_hits);

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       color: #1a1a2e; background: #fafafa; padding: 2rem; max-width: 1100px; margin: 0 auto; }}
h1 {{ font-size: 1.5rem; font-weight: 600; margin-bottom: 0.25rem; }}
.meta {{ color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }}
.stats {{ display: flex; gap: 2rem; margin-bottom: 1.5rem; flex-wrap: wrap; }}
.stat {{ background: #fff; border: 1px solid #e0e0e0; border-radius: 6px; padding: 0.75rem 1.25rem; }}
.stat .val {{ font-size: 1.4rem; font-weight: 700; color: #16213e; }}
.stat .lbl {{ font-size: 0.75rem; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }}
.plot {{ background: #fff; border: 1px solid #e0e0e0; border-radius: 6px; padding: 1rem; margin-bottom: 1.5rem; }}
.row {{ display: flex; gap: 1.5rem; flex-wrap: wrap; }}
.row > .plot {{ flex: 1; min-width: 300px; }}
table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; }}
th {{ text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #16213e;
     font-weight: 600; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.05em; color: #555; }}
td {{ padding: 0.4rem 0.75rem; border-bottom: 1px solid #eee; }}
tr:hover td {{ background: #f5f5ff; }}
.sig {{ color: #c62828; font-weight: 600; }}
svg {{ width: 100%; height: auto; }}
footer {{ margin-top: 2rem; color: #aaa; font-size: 0.7rem; text-align: center; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Traits: {traits} &middot; Masks: {masks}</p>
<div class="stats">
  <div class="stat"><div class="val">{n_samples}</div><div class="lbl">Samples</div></div>
  <div class="stat"><div class="val">{n_rare}</div><div class="lbl">Rare variants</div></div>
  <div class="stat"><div class="val">{n_genes}</div><div class="lbl">Gene-sets tested</div></div>
  <div class="stat"><div class="val sig">{n_sig}</div><div class="lbl">Significant</div></div>
</div>
<div class="plot">
  <h3 style="font-size:0.85rem;margin-bottom:0.5rem;">Manhattan — STAAR-O</h3>
  {manhattan}
</div>
<div class="row">
  <div class="plot">
    <h3 style="font-size:0.85rem;margin-bottom:0.5rem;">QQ Plot</h3>
    {qq}
  </div>
</div>
{table}
<footer>Generated by FAVOR CLI</footer>
</body>
</html>"#,
        traits = traits.join(", "),
        masks = masks.join(", "),
    );

    std::fs::write(output_dir.join("summary.html"), html)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Manhattan plot
// ---------------------------------------------------------------------------

fn layout_points(results: &[(MaskType, Vec<GeneResult>)]) -> Vec<PlotPoint> {
    let offsets = chrom_offsets();
    let mut points = Vec::new();

    for (_, genes) in results {
        for g in genes {
            let p = g.staar.staar_o;
            if !p.is_finite() || p <= 0.0 || p > 1.0 { continue; }
            let chrom = g.chromosome.strip_prefix("chr").unwrap_or(&g.chromosome);
            let (idx, offset) = match offsets.get(chrom) {
                Some(v) => *v,
                None => continue,
            };
            let midpoint = (g.start as f64 + g.end as f64) / 2.0;
            points.push(PlotPoint {
                x: offset as f64 + midpoint,
                y: -p.log10(),
                chrom_idx: idx,
                label: g.gene_symbol.clone(),
            });
        }
    }
    points
}

fn chrom_offsets() -> HashMap<String, (usize, u64)> {
    let mut map = HashMap::new();
    let mut offset = 0u64;
    for (i, &(name, size)) in CHROMS.iter().enumerate() {
        map.insert(name.to_string(), (i, offset));
        offset += size;
    }
    map
}

fn genome_length() -> f64 {
    CHROMS.iter().map(|(_, s)| *s as f64).sum()
}

fn manhattan_svg(points: &[PlotPoint]) -> String {
    let w = 960.0_f64;
    let h = 300.0_f64;
    let ml = 55.0; let mr = 15.0; let mt = 10.0; let mb = 40.0;
    let pw = w - ml - mr;
    let ph = h - mt - mb;

    let genome = genome_length();
    let y_max = points.iter().map(|p| p.y).fold(6.0_f64, f64::max).ceil() + 1.0;

    let colors = ["#4361ee", "#adb5bd"];
    let sig_line = -SIGNIFICANCE.log10();
    let sug_line = -SUGGESTIVE.log10();

    let mut svg = format!(
        r##"<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">"##
    );

    // Axes
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{}" x2="{}" y2="{}" stroke="#ccc" stroke-width="0.5"/>"##,
        mt, ml + pw, mt
    ));
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{}" x2="{ml}" y2="{mt}" stroke="#333" stroke-width="1"/>"##,
        mt + ph
    ));
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{}" x2="{}" y2="{}" stroke="#333" stroke-width="1"/>"##,
        mt + ph, ml + pw, mt + ph
    ));

    // Y tick labels
    let mut y_tick = 0.0;
    while y_tick <= y_max {
        let py = mt + ph - (y_tick / y_max) * ph;
        svg.push_str(&format!(
            r##"<text x="{}" y="{}" text-anchor="end" font-size="9" fill="#555">{}</text>"##,
            ml - 6.0, py + 3.0, y_tick as i32
        ));
        svg.push_str(&format!(
            r##"<line x1="{ml}" y1="{py}" x2="{}" y2="{py}" stroke="#eee" stroke-width="0.5"/>"##,
            ml + pw
        ));
        y_tick += if y_max > 20.0 { 5.0 } else { 2.0 };
    }

    // Y axis label
    svg.push_str(&format!(
        r##"<text x="14" y="{}" transform="rotate(-90 14 {})" text-anchor="middle" font-size="10" fill="#333">&minus;log&#x2081;&#x2080;(p)</text>"##,
        mt + ph / 2.0, mt + ph / 2.0
    ));

    // Chromosome labels
    let offsets = chrom_offsets();
    for &(name, size) in CHROMS {
        if let Some(&(_, off)) = offsets.get(name) {
            let cx = ml + ((off as f64 + size as f64 / 2.0) / genome) * pw;
            let label = if CHROMS.len() > 20 && name.len() > 1 && name != "X" && name != "Y" {
                if name.parse::<u32>().unwrap_or(0) % 2 == 0 { name } else { "" }
            } else { name };
            if !label.is_empty() {
                svg.push_str(&format!(
                    r##"<text x="{cx}" y="{}" text-anchor="middle" font-size="8" fill="#777">{label}</text>"##,
                    mt + ph + 14.0
                ));
            }
        }
    }

    // X axis label
    svg.push_str(&format!(
        r##"<text x="{}" y="{}" text-anchor="middle" font-size="10" fill="#333">Chromosome</text>"##,
        ml + pw / 2.0, h - 4.0
    ));

    // Significance thresholds
    let sig_y = mt + ph - (sig_line / y_max) * ph;
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{sig_y}" x2="{}" y2="{sig_y}" stroke="#c62828" stroke-width="0.8" stroke-dasharray="4 3"/>"##,
        ml + pw
    ));
    if sug_line < y_max {
        let sug_y = mt + ph - (sug_line / y_max) * ph;
        svg.push_str(&format!(
            r##"<line x1="{ml}" y1="{sug_y}" x2="{}" y2="{sug_y}" stroke="#ff9800" stroke-width="0.5" stroke-dasharray="2 3"/>"##,
            ml + pw
        ));
    }

    // Data points
    for p in points {
        let px = ml + (p.x / genome) * pw;
        let py = mt + ph - (p.y.min(y_max) / y_max) * ph;
        let color = colors[p.chrom_idx % 2];
        let r = if p.y >= sig_line { 3.0 } else { 1.8 };
        let opacity = if p.y >= sig_line { 0.9 } else { 0.5 };
        svg.push_str(&format!(
            r##"<circle cx="{px:.1}" cy="{py:.1}" r="{r}" fill="{color}" opacity="{opacity}"/>"##
        ));
    }

    // Labels for significant hits
    let mut labeled: Vec<&PlotPoint> = points.iter().filter(|p| p.y >= sig_line).collect();
    labeled.sort_by(|a, b| b.y.partial_cmp(&a.y).unwrap_or(std::cmp::Ordering::Equal));
    labeled.truncate(15);
    for p in &labeled {
        let px = ml + (p.x / genome) * pw;
        let py = mt + ph - (p.y.min(y_max) / y_max) * ph;
        svg.push_str(&format!(
            r##"<text x="{}" y="{}" font-size="7" fill="#c62828" text-anchor="start" transform="rotate(-35 {} {})">{}</text>"##,
            px + 3.0, py - 4.0, px + 3.0, py - 4.0, p.label
        ));
    }

    svg.push_str("</svg>");
    svg
}

// ---------------------------------------------------------------------------
// QQ plot
// ---------------------------------------------------------------------------

fn qq_svg(pvalues: &[f64]) -> String {
    let w = 360.0_f64;
    let h = 360.0_f64;
    let ml = 50.0; let mr = 15.0; let mt = 10.0; let mb = 45.0;
    let pw = w - ml - mr;
    let ph = h - mt - mb;

    let mut valid: Vec<f64> = pvalues.iter()
        .filter(|p| p.is_finite() && **p > 0.0 && **p <= 1.0)
        .copied()
        .collect();
    valid.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));

    if valid.is_empty() {
        return r##"<svg viewBox="0 0 360 360" xmlns="http://www.w3.org/2000/svg"><text x="180" y="180" text-anchor="middle" font-size="12" fill="#999">No valid p-values</text></svg>"##.into();
    }

    let n = valid.len();
    let observed: Vec<f64> = valid.iter().map(|p| -p.log10()).collect();
    let expected: Vec<f64> = (0..n)
        .map(|i| -((i as f64 + 0.5) / n as f64).log10())
        .collect();

    let axis_max = observed.last().copied().unwrap_or(1.0)
        .max(*expected.last().unwrap_or(&1.0))
        .ceil() + 0.5;

    let colors = ["#4361ee", "#adb5bd"];

    let mut svg = format!(
        r##"<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">"##
    );

    // Identity line
    let x0 = ml; let y0 = mt + ph;
    let x1 = ml + pw; let y1 = mt;
    svg.push_str(&format!(
        r##"<line x1="{x0}" y1="{y0}" x2="{x1}" y2="{y1}" stroke="#ccc" stroke-width="1"/>"##
    ));

    // Axes
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{}" x2="{ml}" y2="{mt}" stroke="#333" stroke-width="1"/>"##,
        mt + ph
    ));
    svg.push_str(&format!(
        r##"<line x1="{ml}" y1="{}" x2="{}" y2="{}" stroke="#333" stroke-width="1"/>"##,
        mt + ph, ml + pw, mt + ph
    ));

    // Ticks
    let tick_step = if axis_max > 20.0 { 5.0 } else if axis_max > 8.0 { 2.0 } else { 1.0 };
    let mut t = 0.0;
    while t <= axis_max {
        let px = ml + (t / axis_max) * pw;
        let py = mt + ph - (t / axis_max) * ph;
        svg.push_str(&format!(
            r##"<text x="{px}" y="{}" text-anchor="middle" font-size="9" fill="#555">{}</text>"##,
            mt + ph + 14.0, t as i32
        ));
        svg.push_str(&format!(
            r##"<text x="{}" y="{}" text-anchor="end" font-size="9" fill="#555">{}</text>"##,
            ml - 6.0, py + 3.0, t as i32
        ));
        t += tick_step;
    }

    // Axis labels
    svg.push_str(&format!(
        r##"<text x="{}" y="{}" text-anchor="middle" font-size="10" fill="#333">Expected &minus;log&#x2081;&#x2080;(p)</text>"##,
        ml + pw / 2.0, h - 4.0
    ));
    svg.push_str(&format!(
        r##"<text x="12" y="{}" transform="rotate(-90 12 {})" text-anchor="middle" font-size="10" fill="#333">Observed &minus;log&#x2081;&#x2080;(p)</text>"##,
        mt + ph / 2.0, mt + ph / 2.0
    ));

    // Points (subsample if too many)
    let step = if n > 2000 { n / 2000 } else { 1 };
    for i in (0..n).step_by(step) {
        let px = ml + (expected[i] / axis_max) * pw;
        let py = mt + ph - (observed[i] / axis_max) * ph;
        let color = colors[i % 2];
        svg.push_str(&format!(
            r##"<circle cx="{px:.1}" cy="{py:.1}" r="1.5" fill="{color}" opacity="0.5"/>"##
        ));
    }
    // Always draw the tail (most significant) without subsampling
    for i in n.saturating_sub(50)..n {
        let px = ml + (expected[i] / axis_max) * pw;
        let py = mt + ph - (observed[i] / axis_max) * ph;
        svg.push_str(&format!(
            r##"<circle cx="{px:.1}" cy="{py:.1}" r="2" fill="#c62828" opacity="0.8"/>"##
        ));
    }

    svg.push_str("</svg>");
    svg
}

// ---------------------------------------------------------------------------
// Top hits table
// ---------------------------------------------------------------------------

struct HitRecord {
    mask: String,
    gene: String,
    chromosome: String,
    n_variants: u32,
    cumulative_mac: u32,
    staar_o: f64,
    burden: f64,
    skat: f64,
    acat_v: f64,
}

fn top_genes(results: &[(MaskType, Vec<GeneResult>)], threshold: f64) -> Vec<HitRecord> {
    let mut hits: Vec<HitRecord> = results.iter().flat_map(|(mask, genes)| {
        genes.iter().filter(|g| g.staar.staar_o < threshold).map(|g| HitRecord {
            mask: mask.file_stem(),
            gene: g.gene_symbol.clone(),
            chromosome: g.chromosome.clone(),
            n_variants: g.n_variants,
            cumulative_mac: g.cumulative_mac,
            staar_o: g.staar.staar_o,
            burden: g.staar.burden_1_25,
            skat: g.staar.skat_1_25,
            acat_v: g.staar.acat_v_1_25,
        })
    }).collect();
    hits.sort_by(|a, b| a.staar_o.partial_cmp(&b.staar_o).unwrap_or(std::cmp::Ordering::Equal));
    hits
}

fn hits_table(hits: &[HitRecord]) -> String {
    if hits.is_empty() {
        return "<p style='color:#888;margin-top:1rem;'>No genome-wide significant genes.</p>".into();
    }

    let mut html = String::from(
        r#"<div class="plot" style="overflow-x:auto;">
<h3 style="font-size:0.85rem;margin-bottom:0.5rem;">Significant Genes (STAAR-O &lt; 2.5×10⁻⁶)</h3>
<table>
<thead><tr>
<th>Mask</th><th>Gene</th><th>Chr</th><th>Variants</th><th>cMAC</th>
<th>STAAR-O</th><th>Burden</th><th>SKAT</th><th>ACAT-V</th>
</tr></thead><tbody>"#
    );

    for h in hits {
        html.push_str(&format!(
            "<tr><td>{}</td><td><b>{}</b></td><td>{}</td><td>{}</td><td>{}</td>\
             <td class='sig'>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            h.mask, h.gene, h.chromosome, h.n_variants, h.cumulative_mac,
            fmt_p(h.staar_o), fmt_p(h.burden), fmt_p(h.skat), fmt_p(h.acat_v),
        ));
    }

    html.push_str("</tbody></table></div>");
    html
}

fn fmt_p(p: f64) -> String {
    if p.is_nan() { "—".into() }
    else if p < 1e-300 { "&lt;1e-300".into() }
    else { format!("{:.2e}", p) }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn collect_pvalues(results: &[(MaskType, Vec<GeneResult>)]) -> Vec<f64> {
    results.iter()
        .flat_map(|(_, genes)| genes.iter().map(|g| g.staar.staar_o))
        .filter(|p| p.is_finite() && *p > 0.0 && *p <= 1.0)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::score_test::StaarResult;

    fn gene(chr: &str, start: u32, p: f64) -> GeneResult {
        GeneResult {
            ensembl_id: format!("ENSG{start}"),
            gene_symbol: format!("GENE{start}"),
            chromosome: chr.into(),
            start,
            end: start + 10000,
            n_variants: 5,
            cumulative_mac: 10,
            staar: StaarResult {
                burden_1_25: p * 2.0, burden_1_1: p * 3.0,
                skat_1_25: p * 1.5, skat_1_1: p * 2.5,
                acat_v_1_25: p * 1.2, acat_v_1_1: p * 2.0,
                per_annotation: Vec::new(),
                staar_b_1_25: p, staar_b_1_1: p,
                staar_s_1_25: p, staar_s_1_1: p,
                staar_a_1_25: p, staar_a_1_1: p,
                acat_o: p, staar_o: p,
            },
        }
    }

    #[test]
    fn manhattan_svg_renders() {
        let results = vec![
            (MaskType::PLof, vec![
                gene("1", 50_000_000, 1e-8),
                gene("2", 100_000_000, 0.05),
                gene("22", 30_000_000, 1e-3),
            ]),
        ];
        let svg = manhattan_svg(&layout_points(&results));
        assert!(svg.contains("<svg"));
        assert!(svg.contains("</svg>"));
        assert!(svg.contains("circle"));
    }

    #[test]
    fn qq_svg_renders() {
        let pvals = vec![0.5, 0.1, 0.01, 0.001, 1e-6, 1e-10];
        let svg = qq_svg(&pvals);
        assert!(svg.contains("<svg"));
        assert!(svg.contains("circle"));
    }

    #[test]
    fn top_genes_filters_significant() {
        let results = vec![
            (MaskType::PLof, vec![
                gene("1", 100, 1e-8),
                gene("1", 200, 0.5),
            ]),
        ];
        let hits = top_genes(&results, 2.5e-6);
        assert_eq!(hits.len(), 1);
        assert!(hits[0].staar_o < 2.5e-6);
    }

    #[test]
    fn empty_results_no_panic() {
        let results: Vec<(MaskType, Vec<GeneResult>)> = Vec::new();
        let svg = manhattan_svg(&layout_points(&results));
        assert!(svg.contains("</svg>"));
        let qq = qq_svg(&[]);
        assert!(qq.contains("No valid p-values"));
    }
}
